version: "3.8"

services:
  api:
    image: ${DOCKER_REGISTRTY_SERVER}/docker-gs-ping
    restart: always
    ports:
      - "8080:8080"

  ui:
      image: ${DOCKER_REGISTRTY_SERVER}/react-app
      restart: always
      ports:
        - "8009:80"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
      - ui
    ports:
      - 80:80